// templates/agora/ui-agora01/src/lib/components/Info.tsx
import Header from './Header'

export const Info = () => {
    return (
        <>
            <header>
                <Header title="info" />
            </header>

            <main className="mt-3">
                <section id="info-content">
                    <article className="m-4">
                        <p className="p-2 prose md:prose-lg lg:prose-xl prose-stone">
                            This micro front end application allows you to read published and approved posts without
                            being able to apply any changes.
                        </p>
                        <p className="p-2 prose md:prose-lg lg:prose-xl prose-stone">
                            To read the posts you will need to go back to the home page and select the link that
                            leads to the posts.
                        </p>
                        <p className="p-2 prose md:prose-lg lg:prose-xl prose-stone">
                            Everything related to post creation, compliance and quality checks, publication,
                            accreditation, deprecation and any other administrative activity will be carried out
                            thanks to a graphical interface developed in the back-end of the application.
                        </p>
                        <p className="p-2 prose md:prose-lg lg:prose-xl prose-stone">Thank you.</p>
                    </article>
                </section>
            </main>
        </>
    )
}

// templates/agora/ui-agora08/src/routes/info/+page.svelte
<div class="agora">
	<div class="navbar">
		<header id="info-title" class="items-center justify-center">
			<h5 class="m-4 font-bold text-cyan-200 uppercase">info</h5>
			<nav id="info-nav" class="my-2">
				<div>
					<a href="/">home</a>
				</div>
			</nav>
		</header>
	</div>
	<div class="flex items-center justify-center">
		<main class="mt-52">
			<section id="info-content">
				<article class="m-4">
					<p class="prose md:prose-lg lg:prose-xl prose-stone p-2">
						This micro front end application allows you to read published and approved posts without
						being able to apply any changes.
					</p>
					<p class="prose md:prose-lg lg:prose-xl prose-stone p-2">
						To read the posts you will need to go back to the home page and select the link that
						leads to the posts.
					</p>
					<p class="prose md:prose-lg lg:prose-xl prose-stone p-2">
						Everything related to post creation, compliance and quality checks, publication,
						accreditation, deprecation and any other administrative activity will be carried out
						thanks to a graphical interface developed in the back-end of the application.
					</p>
					<p class="prose md:prose-lg lg:prose-xl prose-stone p-2">Thank you.</p>
				</article>
			</section>
		</main>
	</div>
</div>
