// templates/agora/ui-agora01/src/lib/components/Counter.tsx
import { FC, useState } from "react"
import { Plus } from "lucide-react"

export const Counter: FC = () => {
  const [count, setCount] = useState<number>(0)

  return (
    <>
      <h3 className="mb-2 prose-lg md:prose-xl lg:prose-2xl prose-slate">
        increment button
      </h3>
      <button onClick={() => setCount((count) => count + 1)}>
        <Plus color="#777" size={32} />
      </button>
      <output className="block m-4 text-2xl md:text-4xl lg:text-6xl">
        {count}
      </output>
    </>
  )
}

// templates/agora/ui-agora07/src/lib/components/Counter.svelte
<script lang="ts">
  import { Plus } from "lucide-svelte"

  let count: number = $state(0)
  const increment = () => {
    count += 1
  }
</script>

<button class="text-cyan-400 count-button" onclick={increment}>
  <Plus />
</button>

<output id="counter-view" class="block mt-4 text-2xl text-slate-400">
  count is {count}
</output>
