// templates/agora/ui-agora03/src/app/app.component.ts
import { Component } from "@angular/core"
import { RouterOutlet } from "@angular/router"

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <header class="flex justify-center items-center m-4">
      <h3 class="font-thin text-cyan-400 uppercase">
        {{ title }}
      </h3>
    </header>

    <router-outlet />
  `,
  styles: [],
})
export class AppComponent {
  title = "Agora"
}

// templates/agora/ui-agora07/src/App.svelte
<script lang="ts">
  import ApiPostsCall from "./lib/ApiPostsCall.svelte"
  import ApiSanctumCsrfCookieCall from "./lib/ApiSanctumCsrfCookieCall.svelte"
</script>

<main>
  <header class="container sticky top-0 z-40 max-w-dvw">
    <div class="flex justify-center items-center">
      <h3 class="m-4 font-thin text-cyan-400 uppercase">Agora</h3>
    </div>
  </header>

  <div class="card">
    <ApiSanctumCsrfCookieCall />
    <ApiPostsCall />
  </div>
</main>
